// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultDir():Promise<string>;

export function GetIps():Promise<Array<string>>;

export function GetServerPort():Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDir(arg1:string):Promise<void>;

export function OpenFilesDialog():Promise<Array<string>>;
