// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultDir() {
  return window['go']['main']['App']['GetDefaultDir']();
}

export function GetIps() {
  return window['go']['main']['App']['GetIps']();
}

export function GetServerPort() {
  return window['go']['main']['App']['GetServerPort']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDir(arg1) {
  return window['go']['main']['App']['OpenFileDir'](arg1);
}

export function OpenFilesDialog() {
  return window['go']['main']['App']['OpenFilesDialog']();
}
